apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
  labels:
    app: pingpong
spec:
  selector:
    matchLabels:
      app: pingpong    
  replicas: 5
  template:
    metadata:
      labels:
        app: "pingpong"
    spec:
      containers:
        - name: pingpong
          image: "robertokbr/pingpong:v4"
          envFrom:
            - configMapRef:
                name: pingpong-env
          