apiVersion: v1
kind: Pod
metadata:
  name: pingpong
  labels:
    app: pingpong
spec:
  containers:
  - name: pingpong
    image: "robertokbr/pingpong:latest"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
