apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pingpong
  labels:
    app: pingpong
spec:
  selector:
    matchLabels: 
      app: pingpong
  replicas: 2
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: "robertokbr/pingpong:latest"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080