apiVersion: v1
kind: Service
metadata:
  name: pingpong-service
spec:
  selector:
    app: pingpong
  type: LoadBalancer
  ports: 
  - name: pingpong-service
    port: 8080
    targetPort: 8080
    protocol: TCP